// <auto-generated />
using Levi9.CommerceSync.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Levi9.CommerceSync.Domain.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20230522122832_DataMigration")]
    partial class DataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Levi9.CommerceSync.Domain.Model.SyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SyncStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdate = "000000000000000000",
                            ResourceType = "PRODUCT"
                        },
                        new
                        {
                            Id = 2,
                            LastUpdate = "000000000000000000",
                            ResourceType = "CLIENT"
                        },
                        new
                        {
                            Id = 3,
                            LastUpdate = "000000000000000000",
                            ResourceType = "DOCUMENT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
